### ISSUE TITLE
To-do list for KubeVela v1.2

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/terraform-controller#173]
- [x] https://github.com/oam-dev/kubevela/issues/2697
- [x] https://github.com/oam-dev/kubevela/issues/2694
- [x] https://github.com/oam-dev/kubevela/issues/2693
- [x] https://github.com/oam-dev/kubevela/issues/2670
- [x] https://github.com/oam-dev/kubevela/issues/2636
- [x] https://github.com/oam-dev/kubevela/issues/2595
- [x] https://github.com/oam-dev/kubevela/issues/2442
